---
title: "Resource backed loans"
output: 
  html_notebook:
    number_sections: yes
    toc: true
    toc_depth: 3
    toc_float: true
    theme: cosmo
    highlight: kate
    smart: true
    code_folding: hide
date: '`r Sys.Date()`'
---


```{r, message=FALSE}
rm(list = ls())
library(tidyverse); library(readxl)
source("../../Functions/Cleaning Functions/Clean Chars.R")
source("../../Functions/Cleaning Functions/Reconcile Values Using Lookups.R")

source("../../Functions/Pipeline Functions/Add Raw Vals to Reconcile Sheet.R")
source("../../Functions/Pipeline Functions/Update Lookup using Reconcile Sheet.R")


rblIds <- read_excel("Workshop Data/Aid Data/AidData RBL subset.xlsx", sheet = "ChinaRBL_subset") %>% 
    select(1)

chinaFinance <- read_excel("Workshop Data/Aid Data/GlobalChineseOfficialFinanceDataset_v1.xlsx", sheet = "ChineseOfficialFinance1.0") %>% 
    select(projectID = project_id, country = recipient_condensed, sector = crs_sector_code, year, status, amount = usd_current, interest = interest_rate, term = maturity, grantProportion = grant_element) %>% 
    filter(sector %in% c(230, 320, 430)) %>% 
    mutate(country = cleanValues(country, "Country"))

rgiScores <- read_csv("../../Data Cleaning/Secondary Data/Countries/Data/RGI Sources/RGI_scores.csv") %>% 
    gather(key = "country", value = "value", 3:91) %>% 
    filter(!str_detect(country, "mining")) %>% 
    mutate(level = str_replace_all(level, "1\\) |2\\) |3\\) ", "") %>% 
               str_replace_all(., "2017 Resource Governance Index", "Overall RGI Score"),
           country = str_replace_all(country, "\\(oil and gas\\)|\\(Alberta\\)|\\(Western\\)", "")) %>% ##replace any countries that have two (use oil as default)
    mutate(country = cleanValues(country, "Country"))

chinaFinance %>% 
    filter(is.na(country))
```

```{r}
sum(is.na(chinaFinance$interest))
```

```{r}
rgiFinal <- bind_rows(rgiScores, rgiBlurb) %>% 
    filter(!str_detect(country, "mining")) %>% 
    mutate(level = str_replace_all(level, "1\\) |2\\) |3\\) ", "") %>% 
               str_replace_all(., "2017 Resource Governance Index", "Overall RGI Score"),
           country = str_replace_all(country, "\\(oil and gas\\)|\\(Alberta\\)|\\(Western\\)", "")) %>% ##replace any countries that have two (use oil as default)
    mutate_at(1:3, cleanCharacters) %>% 
    mutate(country = cleanValues(country, "Country"),
           indicatorName = "RGI") %>% 
    select(indicatorName, country, category = level, value) %>% 
    arrange(country, category)
```

