---
title: "Create Nigeria Data"
author: |
    | Hari Subhash
    | Data Scientist @NRGI
output:
  html_notebook:
    number_sections: yes
    code_folding: hide
    highlight: kate
    smart: yes
    theme: cosmo
  html_document:
    df_print: paged
    toc: yes
    toc_depth: '3'
date: '`r Sys.Date()`'
---

Load data

```{r, message=FALSE}
rm(list = ls())
library(tidyverse); library(googlesheets); library(readxl)


sourceData <- read_csv("/Users/hsubhash/Documents/GitHub/resource-project-data/Data Cleaning/All Data Backups/Current website data/allSource.csv")
projectData <- read_csv("/Users/hsubhash/Documents/GitHub/resource-project-data/Data Cleaning/All Data Backups/Current website data/allProject.csv")
entityData <- read_csv("/Users/hsubhash/Documents/GitHub/resource-project-data/Data Cleaning/All Data Backups/Current website data/allEntity.csv")

projectMeta <- gs_title("Final Secondary - Project") %>% 
    gs_read(ws = "Data", verbose = F)

entityMeta <- gs_title("Final Secondary - Govt. Entities") %>% 
    gs_read(ws = "Data", verbose = F)
```


Filter Nigeria relevant payment data

```{r}
nigeriaIDs <- c(projectData$sourceID[projectData$projectCountry == "Nigeria"], entityData$sourceID[entityData$entityCountry == "Nigeria"]) %>% unique()

nigeriaSources <- sourceData %>% 
    filter(sourceID %in% nigeriaIDs) %>% 
    write_csv(., "data/nigeriaSources.csv")

nigeriaProject <- projectData %>% 
    filter(sourceID %in% nigeriaIDs & projectCountry == "Nigeria") %>% 
    write_csv(., "data/nigeriaProject.csv")

nigeriaEntity <- entityData %>% 
    filter(sourceID %in% nigeriaIDs & entityCountry == "Nigeria") %>% 
    write_csv(., "data/nigeriaEntity.csv")
```

Filter the nigeria relevant project meta data

```{r}
nigeriaMetaProj <- projectMeta %>% 
    filter(projectCountry == "Nigeria") %>% 
    select(-snlPropID) %>% 
    write_csv(., "data/nigeriaProjectMeta.csv")

missingProjects <- nigeriaProject %>% 
    filter(!paste0(projectCountry, projectName) %in% paste0(nigeriaMetaProj$projectCountry, nigeriaMetaProj$projectName)) %>% 
    distinct(projectCountry, projectName) %>% 
    write_csv(., "data/nigeriaMissingProjects.csv")
    
```

Filter the nigeria entity meta data

```{r}
nigeriaMetaEntity <- entityMeta %>% 
    filter(entityCountry == "Nigeria") %>% 
    select(1:10) %>% 
    write_csv(., "data/nigeriaMetaEntity.csv")

missingEntity <- nigeriaEntity %>% 
    filter(!paste0(entityCountry, entityName) %in% paste0(nigeriaEntity$entityCountry, nigeriaEntity$entityName)) %>% 
    distinct(entityCountry, entityName) %>% 
    write_csv(., "data/nigeriaMissingEntity.csv")
```


upload to google drive

```{r, message=FALSE}
source("/Users/hsubhash/Documents/GitHub/resource-project-data/Functions/Clean and backup.R")

updateNigeriaData(sourceData = sourceData, projectData = projectData, entityData = entityData)
```

